apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mongo-pvc.yaml
  - mongo.yaml
  - people-api.yaml

  # Added: HPA & NetworkPolicies
  - hpa-people-api.yaml
  - netpol-people-api-ingress.yaml
  - netpol-people-api-egress.yaml
